### ISSUE TITLE
Possible that person is logged in as wrong user with cookie token

### ISSUE THREAD

**Issue by davidnorth** [technoweenie/restful-authentication#12]
I built a site using 1.1.1 of the plugin. We've had 2 instances where people have reported being logged in as the wrong user. I just found out in at least one of those cases it was after viewing their profile from a bookmark so presumably using authentication by cookie. This fault has been impossible to reproduce. Is it possible users ended up with the same remember_token? The odds of that happening even once seem ridiculously small. Have you heard of anything like this happening?
I've added a unique constraint to that column as a precaution anyway.
Many thanks
David North

**Comment by technoweenie** [comment]
Nope, never had it happen.  But anytime you're querying a record by a string field (like remember_token, email, etc), I tend to add a unique constraint and AR validation anyway.
