### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Vanuan** [technoweenie/restful-authentication#18]
When you were switching to markdown you've missed one thing: converting links.

This is textile:
    "Restful Authentication Generator":http://github.com/technoweenie/restful-authentication
And that's markdown:
    [Restful Authentication Generator](http://github.com/technoweenie/restful-authentication)

**Comment by technoweenie** [comment]
Dude, I just saw that earlier tonight.  Hilarious.

**Comment by Vanuan** [comment]
What a coincidence.
So, I've fixed this, but there is a problem with anchors. It seems like Github filters links.
Vanuan/restful-authentication@2b235806d6471f36cfbf9cc75d28d49102e691a8

**Comment by Vanuan** [comment]
Any chance to pull from me?
