### ISSUE TITLE
uninitialized constant OpenSSL::Digest::SHA1 in rails 3 and ubuntu

### ISSUE THREAD

**Issue by anandkumaragrawal** [technoweenie/restful-authentication#25]
Hi All,

I am trying to integrate restful_authentication plugings into my rails 3 application. I integrated this in windows, but while trying to integrate it to ubuntu I am facing an error "uninitialized constant OpenSSL::Digest::SHA1"

I googled for the solution but still unsuccessful. I am unable to load the file, "require Digest/SHA1"

Now, i tried to run console screen. and tried to check the Digest file by putting print statement, this gives false, while in the irb it returns true.

If anyone has come across such problem

**Comment by technoweenie** [comment]
Ubuntu breaks ruby up into a bunch of smaller packages.  It's likely you don't have the openssl-ruby one or something.  I found [this](http://paulgoscicki.com/archives/2005/09/ruby-on-rails-on-ubuntu/) while doing a bit of googling.
